# Elife Lung Random Forest Binary Classifier predictions

Andrew E. Davidson  
aedaivds@ucsc.edu 2/18/25  

Copyright (c) 2020-2023, Regents of the University of California All rights reserved.   https://polyformproject.org/licenses/noncommercial/1.0.0  

Use the Elife lung Random Forest Binary Classifer we trained using 10 GTEx_TCGA biomarkers on our Tempus Control and Undiluted samples. The Tempus sample are hold out

* ref:    
    - extraCellularRNA/londonCalling2024/jupyterNotebooks/nanoporeAdenocarcinomaBinaryClassification.ipynb
 
**Results**  

Cell [5] : Hugo biomarkers ['FPR3', 'CSF3', 'SLAMF8', 'ENTPD2', 'MAGEE1', 'PCAT19', 'GRIP2', 'PTGIR', 'RND1', 'CHRNB1']

cell [15] : actual counts for each sample. Most of the counts are zero

cell [15] predictions are all Healthy Control
```
predictions:
[0 0 0 0 0 0 0 0 0 0]

yProbability:
[[0.844 0.156]
 [0.886 0.114]
 [0.936 0.064]
 [0.85  0.15 ]
 [0.936 0.064]
 [0.886 0.114]
 [0.918 0.082]
 [0.946 0.054]
 [0.878 0.122]
 [0.86  0.14 ]]
```

In [1]:
import ipynbname

# use display() to print an html version of a data frame
# useful if dataFrame output is not generated by last like of cell
from IPython.display import display

import joblib
# import math
import numpy as np
import os
import pandas as pd
# pd.set_option('display.max_rows', None)

from sklearn.ensemble        import RandomForestClassifier

import sys

notebookName = ipynbname.name()
notebookPath = ipynbname.path()
notebookDir = os.path.dirname(notebookPath)

import logging
# loglevel = "INFO"
loglevel = "WARN"
# logFMT = "%(asctime)s %(levelname)s [thr:%(threadName)s %(name)s %(funcName)s() line:%(lineno)s] [%(message)s]"
logFMT = "%(asctime)s %(levelname)s %(name)s %(funcName)s() line:%(lineno)s] [%(message)s]"
logging.basicConfig(format=logFMT, level=loglevel)    
logger = logging.getLogger(notebookName)

In [2]:
# setting the python path allows us to run python scripts from using
# the CLI. 
ORIG_PYTHONPATH = os.environ['PYTHONPATH']

# deconvolutionModules = notebookPath.parent.joinpath("../../deconvolutionAnalysis/python/")
deconvolutionModules = notebookPath.parent.joinpath("../..")
print("deconvolutionModules: {}\n".format(deconvolutionModules))

PYTHONPATH = ORIG_PYTHONPATH + f':{deconvolutionModules}'
print("PYTHONPATH: {}\n".format(PYTHONPATH))

# intraExtraRNA_POCModules=notebookPath.parent.joinpath("../../intraExtraRNA_POC/python/src")
intraExtraRNA_POCModules=notebookPath.parent.joinpath("/private/home/aedavids/extraCellularRNA/deconvolutionAnalysis/python/tempus/jupyterNotebooks/../../../../intraExtraRNA_POC/python/src")
print("intraExtraRNA_POCModules: {}\n".format(intraExtraRNA_POCModules))

PYTHONPATH = PYTHONPATH + f':{intraExtraRNA_POCModules}'
print("PYTHONPATH: {}\n".format(PYTHONPATH))

os.environ["PYTHONPATH"] = PYTHONPATH
PYTHONPATH = os.environ["PYTHONPATH"]
print("PYTHONPATH: {}\n".format(PYTHONPATH))

# to be able to import our local python files we need to set the sys.path
# https://stackoverflow.com/a/50155834
sys.path.append( str(deconvolutionModules) )
sys.path.append( str(intraExtraRNA_POCModules) )
print("\nsys.path:\n{}\n".format(sys.path))

deconvolutionModules: /private/home/aedavids/extraCellularRNA/deconvolutionAnalysis/python/tempus/jupyterNotebooks/../..

PYTHONPATH: :/private/home/aedavids/extraCellularRNA/src:/private/home/aedavids/extraCellularRNA/deconvolutionAnalysis/python/tempus/jupyterNotebooks/../..

intraExtraRNA_POCModules: /private/home/aedavids/extraCellularRNA/deconvolutionAnalysis/python/tempus/jupyterNotebooks/../../../../intraExtraRNA_POC/python/src

PYTHONPATH: :/private/home/aedavids/extraCellularRNA/src:/private/home/aedavids/extraCellularRNA/deconvolutionAnalysis/python/tempus/jupyterNotebooks/../..:/private/home/aedavids/extraCellularRNA/deconvolutionAnalysis/python/tempus/jupyterNotebooks/../../../../intraExtraRNA_POC/python/src

PYTHONPATH: :/private/home/aedavids/extraCellularRNA/src:/private/home/aedavids/extraCellularRNA/deconvolutionAnalysis/python/tempus/jupyterNotebooks/../..:/private/home/aedavids/extraCellularRNA/deconvolutionAnalysis/python/tempus/jupyterNotebooks/../../../../intraExtraRNA_POC/python/src


sys.path:
['/private/home/aedavids/extraCellularRNA/deconvolutionAnalysis/python/tempus/jupyterNotebooks', '/private/home/aedavids/extraCellularRNA/src', '/private/home/aedavids/miniconda3/envs/extraCellularRNA/lib/python311.zip', '/private/home/aedavids/miniconda3/envs/extraCellularRNA/lib/python3.11', '/private/home/aedavids/miniconda3/envs/extraCellularRNA/lib/python3.11/lib-dynload', '', '/private/home/aedavids/miniconda3/envs/extraCellularRNA/lib/python3.11/site-packages', '/private/home/aedavids/extraCellularRNA/deconvolutionAnalysis/python/tempus/jupyterNotebooks/../..', '/private/home/aedavids/extraCellularRNA/deconvolutionAnalysis/python/tempus/jupyterNotebooks/../../../../intraExtraRNA_POC/python/src']

In [3]:
# import local 
from analysis.utilities import loadDictionary
from analysis.utilities import loadList

from models.mlUtilities import loadEncoder

# Load Random Forest Lung Binary Classifier Trained on Elife Data

In [4]:
modelOut = "/private/groups/kimlab/aedavids/elife/elifeBinaryRandomForestResults.out/model"
modelName = "elife-Lung-Cancer-Health-control-random-forest-GTEx-Lung-biomarkers"
modelPath = f"{modelOut}/{modelName}.joblib"
rfModel = joblib.load(modelPath)
print(f'loaded model: {modelPath}')

/private/home/aedavids/miniconda3/envs/extraCellularRNA/lib/python3.11/site-packages/sklearn/base.py:376: InconsistentVersionWarning: Trying to unpickle estimator DecisionTreeClassifier from version 1.4.0 when using version 1.5.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

loaded model: /private/groups/kimlab/aedavids/elife/elifeBinaryRandomForestResults.out/model/elife-Lung-Cancer-Health-control-random-forest-GTEx-Lung-biomarkers.joblib

/private/home/aedavids/miniconda3/envs/extraCellularRNA/lib/python3.11/site-packages/sklearn/base.py:376: InconsistentVersionWarning: Trying to unpickle estimator RandomForestClassifier from version 1.4.0 when using version 1.5.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [5]:
HUGOFeatureNamesPath = f"{modelOut}/{modelName}_features.txt"
HUGOFeatureNames = loadList(HUGOFeatureNamesPath)
HUGOFeatureNames

['FPR3',
 'CSF3',
 'SLAMF8',
 'ENTPD2',
 'MAGEE1',
 'PCAT19',
 'GRIP2',
 'PTGIR',
 'RND1',
 'CHRNB1']

In [6]:
encoderPath = f'{modelOut}/{modelName}.labelEncoder.txt'
labelEncoder = loadEncoder(encoderPath)
classes = labelEncoder.classes_
print(f'labelEncoder classes :\n{classes}')

labelEncoder classes :
['Healthy donor' 'Lung Cancer']

In [7]:
dataRoot = "/private/groups/kimlab/aedavids/elife/createGTEx_TCGA_elifeDataSets.out/data"
mapDFPath = f'{dataRoot}/mapDF.csv'
mapDF = pd.read_csv(mapDFPath)
print(f'load {mapDFPath}')

load /private/groups/kimlab/aedavids/elife/createGTEx_TCGA_elifeDataSets.out/data/mapDF.csv

In [8]:
print(f'mapDF.shape : {mapDF.shape}')
mapDF.head()

mapDF.shape : (70, 3)

   HUGO_v35            ENSG_v35            ENSG_v39
0  EBNA1BP2  ENSG00000117395.13  ENSG00000117395.13
1    SLAMF8  ENSG00000158714.11  ENSG00000158714.11
2      YOD1  ENSG00000180667.10  ENSG00000180667.11
3   SLC30A1  ENSG00000170385.10  ENSG00000170385.10
4     ROCK2  ENSG00000134318.14  ENSG00000134318.15

# Load the Tempus count data

In [9]:
tempusCountPath = "/private/groups/kimlab/data/tempus/illumina/20241107/create/annotated_norm_counts.csv"
tempusCountDF = pd.read_csv(tempusCountPath)

In [10]:
print(f'tempusCountPath.shape : {tempusCountDF.shape}')
tempusCountDF.iloc[0:5, 0:6]

tempusCountPath.shape : (76539, 38)

,gene_id,gene_name,gene_biotype,SLDK3_T1_100_S1_L007,SLDK3_T1_100K_S2_L007,SLDK3_T1_10K_S3_L007
0,(A)n,(A)n,Microsatellite,0.545009,1.987324,0.569635
1,(AAA)n,(AAA)n,Microsatellite,0.000000,0.000000,0.000000
2,(AAAAAAC)n,(AAAAAAC)n,Microsatellite,0.000000,0.000000,0.000000
3,(AAAAAAG)n,(AAAAAAG)n,Microsatellite,0.000000,0.000000,0.000000
4,(AAAAAAT)n,(AAAAAAT)n,Microsatellite,0.000000,0.000000,0.000000

In [11]:
#tempusMetaDataPath = "/private/groups/kimlab/data/tempus/illumina/20241107/raw/metaDataWithHeader.csv"
tempusMetaDataPath = "/private/groups/kimlab/data/tempus/illumina/20241107/raw/metaDataWithHeader_BUG_FIX.csv"
tempusMetaDF = pd.read_csv(tempusMetaDataPath)

In [12]:
print(f'tempusMetaDF.shape : {tempusMetaDF.shape}')
tempusMetaDF.head(n=7)

tempusMetaDF.shape : (35, 2)

                  sample_id category
0     SLDK3_T1_100K_S2_L007     100K
1      SLDK3_T1_100_S1_L007      100
2      SLDK3_T1_10K_S3_L007      10K
3       SLDK3_T1_1K_S4_L007       1K
4       SLDK3_T1_1M_S5_L007       1M
5  SLDK3_T1_Control_S6_L007  Control
6       SLDK3_T1_UD_S7_L007       UD

# Select the Control and UD samples

In [13]:
selectRows = tempusMetaDF.loc[:, "category"].isin( ['Control', 'UD'] )
tempusSamplesMetaDF = tempusMetaDF.loc[selectRows, :]
print(f'tempusSamplesMetaDF.shape : {tempusSamplesMetaDF.shape}' )
display( tempusSamplesMetaDF)
sampleIds = tempusSamplesMetaDF.loc[:, "sample_id"].to_list()

tempusSamplesMetaDF.shape : (10, 2)

                    sample_id category
5    SLDK3_T1_Control_S6_L007  Control
6         SLDK3_T1_UD_S7_L007       UD
12  SLDK3_T2_Control_S13_L007  Control
13       SLDK3_T2_UD_S14_L007       UD
19  SLDK3_T3_Control_S20_L007  Control
20       SLDK3_T3_UD_S21_L007       UD
26  SLDK3_T5_Control_S27_L007  Control
27       SLDK3_T5_UD_S28_L007       UD
33  SLDK3_T6_Control_S34_L007  Control
34       SLDK3_T6_UD_S35_L007       UD

In [14]:
selectRows = mapDF['HUGO_v35'].isin( HUGOFeatureNames )
sampleMapDF = mapDF.loc[ selectRows, ['HUGO_v35', 'ENSG_v39']]
display(sampleMapDF)
selectGeneIds = sampleMapDF.loc[:, 'ENSG_v39']

   HUGO_v35            ENSG_v39
1    SLAMF8  ENSG00000158714.11
8     GRIP2  ENSG00000144596.13
24   ENTPD2  ENSG00000054179.12
33     RND1  ENSG00000172602.11
50   CHRNB1  ENSG00000170175.11
52     CSF3  ENSG00000108342.13
57   PCAT19   ENSG00000267107.9
58    PTGIR   ENSG00000160013.9
60     FPR3   ENSG00000187474.5
64   MAGEE1   ENSG00000198934.5

In [15]:
selectRows = tempusCountDF['gene_id'].isin( selectGeneIds )
tempusSampleCountsDF =  tempusCountDF.loc[selectRows, ['gene_id'] + sampleIds ]
print(f'tempusSampleCountsDF.shape : {tempusSampleCountsDF.shape}')
tempusSampleCountsDF.set_index('gene_id', inplace=True)
tempusSampleCountsDF

tempusSampleCountsDF.shape : (10, 11)

,SLDK3_T1_Control_S6_L007,SLDK3_T1_UD_S7_L007,SLDK3_T2_Control_S13_L007,SLDK3_T2_UD_S14_L007,SLDK3_T3_Control_S20_L007,SLDK3_T3_UD_S21_L007,SLDK3_T5_Control_S27_L007,SLDK3_T5_UD_S28_L007,SLDK3_T6_Control_S34_L007,SLDK3_T6_UD_S35_L007
gene_id,,,,,,,,,,
ENSG00000054179.12,0.000000,0.0,0.000000,0.560317,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
ENSG00000108342.13,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
ENSG00000144596.13,0.000000,0.0,0.827142,8.404760,1.963970,0.0,0.000000,0.000000,0.000000,5.966516
ENSG00000158714.11,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
ENSG00000160013.9,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,1.546874
ENSG00000170175.11,0.949441,0.0,0.000000,0.560317,0.000000,0.0,0.000000,0.000000,0.000000,1.104910
ENSG00000172602.11,0.000000,0.0,0.000000,0.000000,0.654657,0.0,0.000000,0.000000,0.000000,0.220982
ENSG00000187474.5,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
ENSG00000198934.5,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,1.104910
ENSG00000267107.9,15.191058,0.0,19.851408,24.093646,24.876948,0.0,12.577811,64.441654,5.873856,39.334808

# Make predictions

In [16]:
XDF = tempusSampleCountsDF.transpose()
print(f'XDF.shape : {XDF.shape}')
XDF

XDF.shape : (10, 10)

gene_id,ENSG00000054179.12,ENSG00000108342.13,ENSG00000144596.13,ENSG00000158714.11,ENSG00000160013.9,ENSG00000170175.11,ENSG00000172602.11,ENSG00000187474.5,ENSG00000198934.5,ENSG00000267107.9
SLDK3_T1_Control_S6_L007,0.000000,0.0,0.000000,0.0,0.000000,0.949441,0.000000,0.0,0.00000,15.191058
SLDK3_T1_UD_S7_L007,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.00000,0.000000
SLDK3_T2_Control_S13_L007,0.000000,0.0,0.827142,0.0,0.000000,0.000000,0.000000,0.0,0.00000,19.851408
SLDK3_T2_UD_S14_L007,0.560317,0.0,8.404760,0.0,0.000000,0.560317,0.000000,0.0,0.00000,24.093646
SLDK3_T3_Control_S20_L007,0.000000,0.0,1.963970,0.0,0.000000,0.000000,0.654657,0.0,0.00000,24.876948
SLDK3_T3_UD_S21_L007,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.00000,0.000000
SLDK3_T5_Control_S27_L007,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.00000,12.577811
SLDK3_T5_UD_S28_L007,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.00000,64.441654
SLDK3_T6_Control_S34_L007,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.00000,5.873856
SLDK3_T6_UD_S35_L007,0.000000,0.0,5.966516,0.0,1.546874,1.104910,0.220982,0.0,1.10491,39.334808

In [18]:
predictions  = rfModel.predict(XDF)
print(f'\npredictions:\n{predictions}')
# print(f'\npredictions:\n{labelEncoder.transform(predictions)}')

yProbability = rfModel.predict_proba(XDF)
print(f'\nyProbability:\n{yProbability}')

predictions:
[0 0 0 0 0 0 0 0 0 0]

yProbability:
[[0.844 0.156]
 [0.886 0.114]
 [0.936 0.064]
 [0.85  0.15 ]
 [0.936 0.064]
 [0.886 0.114]
 [0.918 0.082]
 [0.946 0.054]
 [0.878 0.122]
 [0.86  0.14 ]]

/private/home/aedavids/miniconda3/envs/extraCellularRNA/lib/python3.11/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/private/home/aedavids/miniconda3/envs/extraCellularRNA/lib/python3.11/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

In [ ]:
vars( labelEncoder )