# split into tissue specific samples
- [ Data Tables QuickStart Part 3: Understanding sets of data] d(https://support.terra.bio/hc/en-us/articles/360047611871)
- [adding data to a workspace with a template](https://support.terra.bio/hc/en-us/articles/360059242671). see "Sets of data - sample_set table"

In [1]:
import pandas as pd

In [2]:
rootDir = "../data/AnVIL_GTEx_V8_hg38_edu_ucsc_kim_lab"
sampleTSV = rootDir + "/sample.tsv"
sampleDF = pd.read_csv(sampleTSV, delimiter='\t')
sampleDF.head()

,entity:sample_id,bam_file,bam_index,participant,tissue_id,tissue_site_detail
0,GTEX-1117F-0226-SM-5GZZ7,gs://fc-secure-ff8156a3-ddf3-42e4-9211-0fd89da...,gs://fc-secure-ff8156a3-ddf3-42e4-9211-0fd89da...,GTEX-1117F,Adipose_Subcutaneous,Adipose - Subcutaneous
1,GTEX-1117F-0426-SM-5EGHI,gs://fc-secure-ff8156a3-ddf3-42e4-9211-0fd89da...,gs://fc-secure-ff8156a3-ddf3-42e4-9211-0fd89da...,GTEX-1117F,Muscle_Skeletal,Muscle - Skeletal
2,GTEX-1117F-0526-SM-5EGHJ,gs://fc-secure-ff8156a3-ddf3-42e4-9211-0fd89da...,gs://fc-secure-ff8156a3-ddf3-42e4-9211-0fd89da...,GTEX-1117F,Artery_Tibial,Artery - Tibial
3,GTEX-1117F-0626-SM-5N9CS,gs://fc-secure-ff8156a3-ddf3-42e4-9211-0fd89da...,gs://fc-secure-ff8156a3-ddf3-42e4-9211-0fd89da...,GTEX-1117F,Artery_Coronary,Artery - Coronary
4,GTEX-1117F-0726-SM-5GIEN,gs://fc-secure-ff8156a3-ddf3-42e4-9211-0fd89da...,gs://fc-secure-ff8156a3-ddf3-42e4-9211-0fd89da...,GTEX-1117F,Heart_Atrial_Appendage,Heart - Atrial Appendage

In [3]:
tissueTypes = pd.unique( sampleDF.loc[:, "tissue_id"] )

In [4]:
tissueTypes[0]

'Adipose_Subcutaneous'

In [7]:
selectRows = sampleDF.loc[:, "tissue_id"] == tissueTypes[0]
sampleDF.loc[selectRows, :].head()
sampleDF.loc[ selectRows, ['tissue_id',"entity:sample_id"] ].head()

               tissue_id          entity:sample_id
0   Adipose_Subcutaneous  GTEX-1117F-0226-SM-5GZZ7
28  Adipose_Subcutaneous  GTEX-111CU-1826-SM-5GZYN
32  Adipose_Subcutaneous  GTEX-111FC-0226-SM-5N9B8
54  Adipose_Subcutaneous  GTEX-111VG-2326-SM-5N9BK
82  Adipose_Subcutaneous  GTEX-111YS-2426-SM-5GZZQ

In [ ]:
# for tType in tissueTypes:
#     selectRows = sampleDF.loc[:, "tissue_id"] == tType
#     tDF = sampleDF.loc[selectRows, :]
#     path = rootDir + "/" + tType + ".tsv"
#     print(path)
#     tDF.to_csv(path, sep='\t')

```
cat sample_set_entity.tsv
entity:sample_set_id
set-d-4-panc
```

```
(base) $ cat sample_set_membership.tsv 
membership:sample_set_id	sample
set-d-4-panc	GTEX-11GSP-0426-SM-5A5KX
set-d-4-panc	GTEX-11I78-0626-SM-5A5LZ
set-d-4-panc	GTEX-11LCK-0226-SM-5A5M6
set-d-4-panc	GTEX-11NSD-0526-SM-5A5LT
```