# Explore Elife Feature Counts

Andrew E. Davidson  
aedaivds@ucsc.edu 2/18/25  

Copyright (c) 2020-2023, Regents of the University of California All rights reserved. https://polyformproject.org/licenses/noncommercial/1.0.0  

**ref :**
 - intraExtraRNA_POC/jupyterNotebooks/elife/elifeBinaryRandomForestResults.ipynb
 - deconvolutionAnalysis/tempus/jupyterNotebooks/elifeLungRandomForestPredictions.ipynb
 - intraExtraRNA_POC/jupyterNotebooks/elife/gan/clusterAnalysis.ipynb
 - intraExtraRNA_POC/jupyterNotebooks/elife/createGTEx_TCGA_elifeDataSets.ipynb

**Abstract:** 

We used the Lung Binary classifier trained in elifeBinaryRandomForestResults.ipynb to make predict if the tempus Undiluted and Control samples where either Lung cancer or a healthy control. The hyperparameter tunning results using k-fold validation was  0.7515873015873017. The AUC when we trained on all the samples was 1.00

```
HUGO_Genes
['FPR3', 'CSF3', 'SLAMF8', 'ENTPD2', 'MAGEE1', 'PCAT19', 'GRIP2', 'PTGIR', 'RND1', 'CHRNB1']

elifeGenes
['ENSG00000158714.11', 'ENSG00000144596.13', 'ENSG00000054179.12', 'ENSG00000172602.11', 'ENSG00000170175.11', 'ENSG00000108342.13', 'ENSG00000267107.9', 'ENSG00000160013.9', 'ENSG00000187474.5', 'ENSG00000198934.5']
```

When we used this model make predictions on Tempus Undiluted and Control samples. The model predicted all the samples where healthy control. Looking at the Tempus count data, almost all values where zero. We never looked at the actual count data from the elife data.

In general the elife data does not cluster

In [1]:
import ipynbname

# use display() to print an html version of a data frame
# useful if dataFrame output is not generated by last like of cell
from IPython.display import display

import joblib
# import math
#import numpy as np
import os
import pandas as pd
# pd.set_option('display.max_rows', None)

#from sklearn.ensemble        import RandomForestClassifier

import sys

notebookName = ipynbname.name()
notebookPath = ipynbname.path()
notebookDir = os.path.dirname(notebookPath)

import logging
# loglevel = "INFO"
loglevel = "WARN"
# logFMT = "%(asctime)s %(levelname)s [thr:%(threadName)s %(name)s %(funcName)s() line:%(lineno)s] [%(message)s]"
logFMT = "%(asctime)s %(levelname)s %(name)s %(funcName)s() line:%(lineno)s] [%(message)s]"
logging.basicConfig(format=logFMT, level=loglevel)    
logger = logging.getLogger(notebookName)

In [2]:
#  setting the python path allows us to run python scripts from using
# # the CLI. 
ORIG_PYTHONPATH = os.environ['PYTHONPATH']

deconvolutionModules = notebookPath.parent.joinpath("../../../deconvolutionAnalysis/python/")
print("deconvolutionModules: {}\n".format(deconvolutionModules))

PYTHONPATH = ORIG_PYTHONPATH + f':{deconvolutionModules}'
print("PYTHONPATH: {}\n".format(PYTHONPATH))

intraExtraRNA_POCModules=notebookPath.parent.joinpath("../../python/src")
print("intraExtraRNA_POCModules: {}\n".format(intraExtraRNA_POCModules))

PYTHONPATH = PYTHONPATH + f':{intraExtraRNA_POCModules}'
print("PYTHONPATH: {}\n".format(PYTHONPATH))

########
os.environ["PYTHONPATH"] = PYTHONPATH
PYTHONPATH = os.environ["PYTHONPATH"]
print("PYTHONPATH: {}\n".format(PYTHONPATH))

# to be able to import our local python files we need to set the sys.path
# https://stackoverflow.com/a/50155834
sys.path.append( str(deconvolutionModules) )
sys.path.append( str(intraExtraRNA_POCModules) )
print("\nsys.path:\n{}\n".format(sys.path))

deconvolutionModules: /private/home/aedavids/extraCellularRNA/intraExtraRNA_POC/jupyterNotebooks/elife/../../../deconvolutionAnalysis/python

PYTHONPATH: :/private/home/aedavids/extraCellularRNA/src:/private/home/aedavids/extraCellularRNA/intraExtraRNA_POC/jupyterNotebooks/elife/../../../deconvolutionAnalysis/python

intraExtraRNA_POCModules: /private/home/aedavids/extraCellularRNA/intraExtraRNA_POC/jupyterNotebooks/elife/../../python/src

PYTHONPATH: :/private/home/aedavids/extraCellularRNA/src:/private/home/aedavids/extraCellularRNA/intraExtraRNA_POC/jupyterNotebooks/elife/../../../deconvolutionAnalysis/python:/private/home/aedavids/extraCellularRNA/intraExtraRNA_POC/jupyterNotebooks/elife/../../python/src

PYTHONPATH: :/private/home/aedavids/extraCellularRNA/src:/private/home/aedavids/extraCellularRNA/intraExtraRNA_POC/jupyterNotebooks/elife/../../../deconvolutionAnalysis/python:/private/home/aedavids/extraCellularRNA/intraExtraRNA_POC/jupyterNotebooks/elife/../../python/src


sys.path:
['/private/home/aedavids/extraCellularRNA/intraExtraRNA_POC/jupyterNotebooks/elife', '/private/home/aedavids/extraCellularRNA/src', '/private/home/aedavids/miniconda3/envs/extraCellularRNA/lib/python311.zip', '/private/home/aedavids/miniconda3/envs/extraCellularRNA/lib/python3.11', '/private/home/aedavids/miniconda3/envs/extraCellularRNA/lib/python3.11/lib-dynload', '', '/private/home/aedavids/miniconda3/envs/extraCellularRNA/lib/python3.11/site-packages', '/private/home/aedavids/extraCellularRNA/intraExtraRNA_POC/jupyterNotebooks/elife/../../../deconvolutionAnalysis/python', '/private/home/aedavids/extraCellularRNA/intraExtraRNA_POC/jupyterNotebooks/elife/../../python/src']

In [3]:
# local packages
from analysis.utilities import loadList

In [4]:
dataRoot = "/private/groups/kimlab/aedavids/elife/createGTEx_TCGA_elifeDataSets.out/data"
countDFPath = f'{dataRoot}/countDF.csv'
countDF = pd.read_csv(countDFPath, index_col='sample_id') # , index_col=
print(f'load {countDFPath}')

load /private/groups/kimlab/aedavids/elife/createGTEx_TCGA_elifeDataSets.out/data/countDF.csv

In [5]:
print(f'countDF.shape : {countDF.shape}')

countDF.shape : (224, 76555)

In [6]:
countDF.iloc[0:3, 0:5]

                    (A)n  (AAA)n  (AAAAAAC)n  (AAAAAAG)n  (AAAAAAT)n
sample_id
SRR14506659   201.672053     0.0         0.0         0.0         0.0
SRR14506660   110.450773     0.0         0.0         0.0         0.0
SRR14506661  3722.776395     0.0         0.0         0.0         0.0

In [7]:
countDF.iloc[0:3, -5:]

             X8_LINE  X9_LINE      Zaphod    Zaphod2    Zaphod3
sample_id
SRR14506659      0.0      0.0  170.645583  55.847645  24.821176
SRR14506660      0.0      0.0    0.000000   0.000000   0.000000
SRR14506661      0.0      0.0    0.000000   0.000000   0.000000

In [8]:
metaDFPath =  f'{dataRoot}/metaDF.csv'
metaDF = pd.read_csv(metaDFPath, index_col='sample_id')
print(f'load {metaDFPath}')

load /private/groups/kimlab/aedavids/elife/createGTEx_TCGA_elifeDataSets.out/data/metaDF.csv

In [9]:
print(f'metaDF.shape : {metaDF.shape}')
metaDF.head()

metaDF.shape : (224, 1)

                    diagnosis
sample_id
SRR14506659  Esophagus Cancer
SRR14506660  Esophagus Cancer
SRR14506661  Esophagus Cancer
SRR14506662  Esophagus Cancer
SRR14506663  Esophagus Cancer

In [10]:
metaDF.loc[:, 'diagnosis'].unique()

array(['Esophagus Cancer', 'Lung Cancer', 'Liver Cancer',
       'Stomach Cancer', 'Colorectal Cancer', 'Healthy donor'],
      dtype=object)

In [11]:
selectLungIdRows = metaDF.loc[:, 'diagnosis'] == 'Lung Cancer'
lungSampleIds = metaDF.loc[ selectLungIdRows, :].index
lungSampleIds

Index(['SRR14506690', 'SRR14506691', 'SRR14506692', 'SRR14506693',
       'SRR14506694', 'SRR14506695', 'SRR14506696', 'SRR14506697',
       'SRR14506698', 'SRR14506699', 'SRR14506700', 'SRR14506701',
       'SRR14506702', 'SRR14506703', 'SRR14506704', 'SRR14506705',
       'SRR14506706', 'SRR14506707', 'SRR14506708', 'SRR14506709',
       'SRR14506710', 'SRR14506711', 'SRR14506712', 'SRR14506713',
       'SRR14506714', 'SRR14506715', 'SRR14506716', 'SRR14506717',
       'SRR14506718', 'SRR14506719', 'SRR14506720', 'SRR14506721',
       'SRR14506722', 'SRR14506723', 'SRR14506724'],
      dtype='object', name='sample_id')

In [12]:
selectHealthIdRows = metaDF.loc[:, 'diagnosis'] == 'Healthy donor'
healthySampleIds = metaDF.loc[ selectHealthIdRows, :].index
healthySampleIds

Index(['SRR14506843', 'SRR14506844', 'SRR14506845', 'SRR14506846',
       'SRR14506847', 'SRR14506848', 'SRR14506849', 'SRR14506850',
       'SRR14506851', 'SRR14506853', 'SRR14506854', 'SRR14506855',
       'SRR14506856', 'SRR14506857', 'SRR14506858', 'SRR14506859',
       'SRR14506860', 'SRR14506861', 'SRR14506862', 'SRR14506864',
       'SRR14506865', 'SRR14506866', 'SRR14506867', 'SRR14506868',
       'SRR14506869', 'SRR14506870', 'SRR14506871', 'SRR14506872',
       'SRR14506873', 'SRR14506874', 'SRR14506875', 'SRR14506877',
       'SRR14506878', 'SRR14506879', 'SRR14506880', 'SRR14506881',
       'SRR14506882', 'SRR14506883', 'SRR14506884', 'SRR14506885',
       'SRR14506886', 'SRR14506887', 'SRR14506888'],
      dtype='object', name='sample_id')

In [13]:
modelOut = "/private/groups/kimlab/aedavids/elife/elifeBinaryRandomForestResults.out/model"
modelName = "elife-Lung-Cancer-Health-control-random-forest-GTEx-Lung-biomarkers"
HUGOFeatureNamesPath = f"{modelOut}/{modelName}_features.txt"
HUGOFeatureNames = loadList(HUGOFeatureNamesPath)
HUGOFeatureNames

['FPR3',
 'CSF3',
 'SLAMF8',
 'ENTPD2',
 'MAGEE1',
 'PCAT19',
 'GRIP2',
 'PTGIR',
 'RND1',
 'CHRNB1']

In [19]:
mapDFPath =  f'{dataRoot}/mapDF.csv'
mapDF = pd.read_csv(mapDFPath, index_col='HUGO_v35')
print(f'load {mapDFPath}')

load /private/groups/kimlab/aedavids/elife/createGTEx_TCGA_elifeDataSets.out/data/mapDF.csv

In [20]:
print(f'mapDF.shape : {mapDF.shape}')
mapDF.head()

mapDF.shape : (70, 2)

                    ENSG_v35            ENSG_v39
HUGO_v35
EBNA1BP2  ENSG00000117395.13  ENSG00000117395.13
SLAMF8    ENSG00000158714.11  ENSG00000158714.11
YOD1      ENSG00000180667.10  ENSG00000180667.11
SLC30A1   ENSG00000170385.10  ENSG00000170385.10
ROCK2     ENSG00000134318.14  ENSG00000134318.15

In [26]:
selectRows = mapDF.index.isin( HUGOFeatureNames )
sampleMapDF = mapDF.loc[ selectRows, ['ENSG_v39']]
display(sampleMapDF)
selectGeneIds = sampleMapDF.loc[:, 'ENSG_v39'].values
selectGeneIds

                    ENSG_v39
HUGO_v35
SLAMF8    ENSG00000158714.11
GRIP2     ENSG00000144596.13
ENTPD2    ENSG00000054179.12
RND1      ENSG00000172602.11
CHRNB1    ENSG00000170175.11
CSF3      ENSG00000108342.13
PCAT19     ENSG00000267107.9
PTGIR      ENSG00000160013.9
FPR3       ENSG00000187474.5
MAGEE1     ENSG00000198934.5

array(['ENSG00000158714.11', 'ENSG00000144596.13', 'ENSG00000054179.12',
       'ENSG00000172602.11', 'ENSG00000170175.11', 'ENSG00000108342.13',
       'ENSG00000267107.9', 'ENSG00000160013.9', 'ENSG00000187474.5',
       'ENSG00000198934.5'], dtype=object)

In [27]:
countDF.loc[selectLungIdRows, selectGeneIds]

,ENSG00000158714.11,ENSG00000144596.13,ENSG00000054179.12,ENSG00000172602.11,ENSG00000170175.11,ENSG00000108342.13,ENSG00000267107.9,ENSG00000160013.9,ENSG00000187474.5,ENSG00000198934.5
sample_id,,,,,,,,,,
SRR14506690,1.636995,3.455879,0.000000,2.182660,18.370724,0.363777,3.455879,135.870605,4.547209,1.818884
SRR14506691,0.000000,3.965234,0.000000,0.000000,13.217447,0.000000,10.573958,88.556897,0.000000,0.000000
SRR14506692,0.000000,0.000000,0.000000,9.293481,11.875003,0.516304,15.489135,106.358727,7.744567,6.195654
SRR14506693,0.000000,11.639525,0.000000,2.024265,12.651658,5.060663,28.339713,72.367482,0.000000,4.048530
SRR14506694,0.000000,1.241376,0.000000,0.413792,16.551686,0.000000,4.965506,153.930676,6.620674,15.310309
SRR14506695,3.118462,0.000000,0.623692,3.118462,13.721231,0.000000,11.226462,137.212314,4.365846,0.623692
SRR14506696,3.508385,0.438548,0.000000,1.315644,19.076845,0.657822,16.445556,126.959693,1.973467,3.289111
SRR14506697,4.863739,0.000000,0.000000,0.000000,39.604735,0.000000,21.539417,142.438083,0.000000,5.558559
SRR14506698,5.581392,0.000000,0.000000,0.000000,7.813949,0.000000,52.465085,49.116250,3.348835,0.000000
SRR14506699,3.142140,0.785535,0.000000,1.571070,27.493721,0.000000,12.568558,65.984931,2.356605,0.785535
SRR14506700,4.806996,0.000000,0.000000,0.000000,11.416616,0.000000,116.569658,55.280456,3.004373,1.802624
SRR14506701,1.191512,4.170290,0.000000,0.000000,16.681161,0.000000,7.149069,216.259338,8.340581,5.361802
SRR14506702,0.000000,0.000000,0.000000,0.000000,8.495631,0.000000,23.586554,44.154923,9.054554,9.725261
SRR14506703,8.103171,0.000000,0.000000,0.000000,8.778435,0.000000,40.178222,62.461941,0.000000,13.167653
SRR14506704,3.711451,0.000000,0.618575,1.855726,9.897203,0.000000,52.578891,28.454458,2.474301,0.618575
SRR14506705,0.000000,0.000000,0.000000,0.000000,32.431156,0.000000,27.310447,76.241666,0.000000,0.000000
SRR14506706,7.387051,0.000000,0.000000,0.000000,33.703420,0.000000,0.000000,112.190835,16.159174,0.000000
SRR14506707,2.185741,0.000000,0.000000,0.242860,15.785905,0.000000,4.128621,100.058354,0.000000,5.585782
SRR14506708,0.000000,12.683863,0.000000,0.000000,52.372080,0.000000,12.274706,84.286316,0.000000,3.682412
SRR14506709,0.000000,0.000000,0.000000,0.000000,11.370999,0.000000,12.002721,54.959827,6.948944,0.000000
SRR14506710,0.000000,0.000000,0.000000,0.000000,7.153797,0.000000,3.576898,131.152937,0.000000,0.000000
SRR14506711,3.919932,0.000000,0.979983,0.000000,28.909496,0.000000,14.209752,164.637132,2.449957,0.489991
SRR14506712,230.926342,4272.137335,1693.459844,1193.119436,846.729922,461.852685,1616.484397,3733.309202,461.852685,2347.751148
SRR14506713,1.400783,1.867711,0.933856,1.867711,18.210184,0.000000,3.268495,190.506538,0.466928,3.268495
SRR14506714,8.715037,0.484169,0.000000,0.000000,30.018462,0.000000,10.167543,116.200497,0.000000,6.778362
SRR14506715,0.000000,0.000000,0.000000,0.000000,43.016389,0.000000,13.058547,138.266966,0.000000,0.000000
SRR14506716,1.944674,34.355912,3.241124,17.502069,17.826181,6.158135,18.474406,96.261377,8.102810,9.399259
SRR14506717,0.000000,1734.091157,55.938424,149.169132,279.692122,727.199518,74.584566,671.261093,111.876849,540.738103
SRR14506718,1.304234,0.869489,0.000000,0.000000,13.042337,0.434745,22.171973,84.775191,9.129636,3.912701
SRR14506719,0.796683,3.186733,0.000000,0.000000,25.493865,0.000000,10.356883,73.294862,0.000000,3.186733
SRR14506720,0.000000,9.200930,0.000000,35.489303,0.000000,0.657209,13.144186,26.288372,3.943256,0.000000
SRR14506721,0.000000,0.000000,0.000000,0.747152,13.448733,0.000000,5.977215,215.179725,0.000000,5.230063
SRR14506722,0.587603,4.113218,0.000000,0.000000,22.328895,0.587603,14.102460,177.455957,0.587603,7.051230
SRR14506723,0.000000,2.344707,0.000000,0.000000,24.853892,3.282589,25.322833,93.319330,6.565179,0.937883
SRR14506724,5.263117,1.503748,2.255622,0.375937,13.533729,0.000000,15.413414,54.510854,5.263117,6.766865

In [28]:
countDF.loc[healthySampleIds, selectGeneIds]

,ENSG00000158714.11,ENSG00000144596.13,ENSG00000054179.12,ENSG00000172602.11,ENSG00000170175.11,ENSG00000108342.13,ENSG00000267107.9,ENSG00000160013.9,ENSG00000187474.5,ENSG00000198934.5
sample_id,,,,,,,,,,
SRR14506843,1.835785,0.917893,0.000000,0.917893,5.507356,0.000000,267.106761,53.237774,55.073559,4.589463
SRR14506844,49.647848,11.127966,0.000000,0.000000,37.663884,0.000000,111.279658,92.447716,65.911798,17.119947
SRR14506845,0.000000,34.349732,0.000000,20.609839,16.487871,0.000000,142.894886,52.211593,54.959571,54.959571
SRR14506846,0.000000,0.000000,4.541199,0.000000,0.000000,0.000000,154.400761,27.247193,0.000000,0.000000
SRR14506847,0.000000,29.101215,0.000000,38.801620,58.202430,9.700405,9.700405,97.004050,0.000000,87.303645
SRR14506848,0.000000,0.000000,39.694282,0.000000,0.000000,0.000000,0.000000,92.619991,0.000000,0.000000
SRR14506849,23.005334,0.000000,0.000000,1.533689,44.476979,0.000000,113.492981,75.150758,65.948624,9.202134
SRR14506850,0.000000,8.259879,0.000000,1.835529,0.000000,0.000000,75.256672,10.095407,1.835529,14.684229
SRR14506851,0.000000,111.606062,0.000000,37.202021,65.103536,0.000000,0.000000,144.157831,0.000000,0.000000
SRR14506853,0.000000,70.457234,9.190074,55.140444,6.126716,0.000000,125.597678,45.950370,24.506864,42.887012
SRR14506854,255.602116,0.000000,0.000000,357.842963,51.120423,0.000000,204.481693,178.921482,0.000000,0.000000
SRR14506855,15.864691,6.345876,6.345876,0.000000,34.902320,0.000000,22.210567,53.939949,85.669330,0.000000
SRR14506856,4.714065,4.714065,14.142194,0.000000,10.606646,0.000000,143.778973,1.178516,0.000000,8.249613
SRR14506857,7.070643,10.605965,7.070643,0.000000,0.000000,0.000000,70.706433,67.171112,21.211930,7.070643
SRR14506858,0.000000,0.000000,0.000000,0.000000,15.436419,0.000000,7.718210,7.718210,0.000000,0.000000
SRR14506859,0.000000,20.347295,0.000000,44.394099,0.000000,0.000000,55.492624,61.041886,0.000000,83.238936
SRR14506860,108.098401,0.000000,0.000000,0.000000,0.000000,0.000000,58.500311,20.347934,5.086984,0.000000
SRR14506861,0.529647,0.000000,0.000000,0.529647,16.419061,0.000000,7.415060,70.972717,2.118589,0.000000
SRR14506862,2.356667,0.000000,0.000000,0.000000,31.579342,0.000000,8.955336,111.234697,4.713335,2.356667
SRR14506864,0.000000,0.000000,0.000000,0.000000,11.166075,0.000000,19.141843,31.105494,3.987884,6.380614
SRR14506865,4.511641,1.899638,0.000000,0.000000,11.635285,0.000000,7.836008,105.667383,12.822559,5.224005
SRR14506866,0.000000,292.458943,0.000000,0.000000,18.868319,0.000000,0.000000,66.039116,0.000000,18.868319
SRR14506867,4.099788,0.819958,0.000000,0.000000,17.219108,0.000000,4.099788,135.292992,0.000000,11.479405
SRR14506868,1.364287,0.000000,0.000000,3.410718,27.967885,4.775005,17.735732,94.135807,4.092861,2.728574
SRR14506869,10.599901,4.364665,0.000000,0.000000,39.905509,0.000000,0.000000,48.011316,0.000000,12.470472
SRR14506870,4.100238,0.000000,0.000000,0.000000,12.300715,0.000000,9.840572,165.649627,3.280191,3.280191
SRR14506871,2.546725,0.000000,0.000000,1.131878,24.335375,0.000000,24.052405,53.198261,4.244542,1.131878
SRR14506872,2.661427,4.790569,0.000000,0.532285,5.855140,4.258283,10.645709,96.875948,18.097705,10.645709
SRR14506873,3.552449,0.000000,0.000000,0.000000,17.762247,0.000000,6.394409,122.914748,4.262939,4.973429
SRR14506874,1.134688,0.000000,0.000000,0.567344,18.155008,0.000000,1.702032,82.264879,7.375472,2.269376
SRR14506875,5.966333,0.000000,0.000000,7.671000,1.704667,0.000000,22.160666,158.533996,5.966333,3.409333
SRR14506877,25.303766,7.952612,2.891859,0.000000,83.140945,0.000000,15.905224,83.863910,10.844471,10.121506
SRR14506878,9.389191,21.908113,4.694596,3.912163,32.862170,0.782433,58.682446,82.155425,18.778383,0.782433
SRR14506879,0.000000,0.000000,0.000000,85.528866,0.000000,0.000000,0.000000,85.528866,0.000000,0.000000
SRR14506880,0.000000,746.723026,0.000000,0.000000,0.000000,0.000000,0.000000,373.361513,0.000000,373.361513
SRR14506881,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,24.759259,173.314811,123.796293
SRR14506882,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,76.894143,349.227566,24.029420
SRR14506883,211.684723,0.000000,0.000000,0.000000,0.000000,0.000000,73.275481,105.842362,0.000000,0.000000
SRR14506884,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,170.438307,83.611245,0.000000,0.000000
SRR14506885,9.639302,0.000000,0.000000,0.535517,16.065503,1.071034,10.710335,102.819217,2.142067,1.606550
SRR14506886,0.000000,0.000000,0.000000,0.000000,23.896795,0.000000,4.779359,63.724785,0.000000,11.151837
SRR14506887,3.834514,1.150354,0.000000,0.000000,18.022217,0.000000,8.435931,65.953645,4.217966,5.368320
SRR14506888,6.550504,0.000000,0.000000,0.000000,18.495541,0.000000,3.853238,192.661884,3.082590,4.623885